version: "0.1"
services:

  # Download files from https://data.ppy.sh
  downloader-service:
    image: downloader
    stdin_open: true
    build:
      context: .
      dockerfile: download.Dockerfile
      args:
        - FILE_NAME=${FILE_NAME}
        - WORKDIR=${WORKDIR}
        - OSU_BEATMAP_DIFFICULTY=${OSU_BEATMAP_DIFFICULTY}
        - OSU_BEATMAPS=${OSU_BEATMAPS}
        - OSU_BEATMAPSETS=${OSU_BEATMAPSETS}
        - OSU_COUNTS=${OSU_COUNTS}
        - OSU_DIFFICULTY_ATTRIBS=${OSU_DIFFICULTY_ATTRIBS}
        - OSU_SCORES=${OSU_SCORES}
        - OSU_USER_STATS=${OSU_USER_STATS}
        - OSU_BEATMAP_DIFFICULTY_ATTRIBS=${OSU_BEATMAP_DIFFICULTY_ATTRIBS}
        - OSU_BEATMAP_FAILTIMES=${OSU_BEATMAP_FAILTIMES}
        - OSU_BEATMAP_PERFORMANCE_BLACKLIST=${OSU_BEATMAP_PERFORMANCE_BLACKLIST}
        - OSU_USER_BEATMAP_PLAYCOUNT=${OSU_USER_BEATMAP_PLAYCOUNT}
        - SAMPLE_USERS=${SAMPLE_USERS}
    volumes:
      - osu-data:/${WORKDIR}

  # Uses files from downloader-service to initialize our mysql database
  mysql-service:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=osu
      - MYSQL_TCP_PORT=${MYSQL_PORT}
    volumes:
      - ./mysql.cnf:/etc/mysql/my.cnf:ro
      - osu-data:/docker-entrypoint-initdb.d
    depends_on:
      - downloader-service
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}

volumes:
  osu-data: