version: "0.1"
services:

  # Download files from https://data.ppy.sh
  downloader-service:
    image: downloader
    build:
      context: .
      dockerfile: download.Dockerfile
      args:
        - FILE_NAME=${FILE_NAME}
        - WORKDIR=${WORKDIR}
    volumes:
      - osu-data:/${WORKDIR}

  # Uses files from downloader-service to initialize our mysql database
  mysql-service:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=osu
      - MYSQL_TCP_PORT=${MYSQL_PORT}
    volumes:
      - ./mysql.cnf:/etc/mysql/my.cnf
      - osu-data:/docker-entrypoint-initdb.d
    depends_on:
      - downloader-service
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}

volumes:
  osu-data: