version: "2.18.1"
services:

  # Download files from https://data.ppy.sh
  osu.mysql.dl:
    image: osu.mysql.dl:${VERSION}_${DATASET}
    stdin_open: true
    container_name: osu.mysql.dl.${VERSION}_${DATASET}
    build:
      context: .
      dockerfile: osu.mysql.dl.Dockerfile
      args:
        - FILE_NAME=${OSU_DB}
        - WORKDIR=osu.mysql.dl
        - OSU_BEATMAP_DIFFICULTY=${OSU_BEATMAP_DIFFICULTY}
        - OSU_BEATMAPS=${OSU_BEATMAPS}
        - OSU_BEATMAPSETS=${OSU_BEATMAPSETS}
        - OSU_COUNTS=${OSU_COUNTS}
        - OSU_DIFFICULTY_ATTRIBS=${OSU_DIFFICULTY_ATTRIBS}
        - OSU_SCORES=${OSU_SCORES}
        - OSU_USER_STATS=${OSU_USER_STATS}
        - OSU_BEATMAP_DIFFICULTY_ATTRIBS=${OSU_BEATMAP_DIFFICULTY_ATTRIBS}
        - OSU_BEATMAP_FAILTIMES=${OSU_BEATMAP_FAILTIMES}
        - OSU_BEATMAP_PERFORMANCE_BLACKLIST=${OSU_BEATMAP_PERFORMANCE_BLACKLIST}
        - OSU_USER_BEATMAP_PLAYCOUNT=${OSU_USER_BEATMAP_PLAYCOUNT}
        - SAMPLE_USERS=${SAMPLE_USERS}
    volumes:
      - osu.mysql.vol:/osu.mysql.dl

  # Uses files from osu.mysql to initialize our mysql database
  osu.mysql:
    image: mysql
    container_name: osu.mysql.${VERSION}_${DATASET}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=osu
      - MYSQL_TCP_PORT=${MYSQL_PORT}
    volumes:
      - ./osu.mysql.cnf:/etc/mysql/my.cnf:ro
      - osu.mysql.vol:/docker-entrypoint-initdb.d
    depends_on:
      osu.mysql.dl:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 3s
      timeout: 3s
      retries: 3
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}

  # Downloads .osu files
  # Will only be activated if profile `files` is activated.
  # > docker compose --profile files up
  osu.files:
    image: osu.files:${VERSION}
    stdin_open: true
    container_name: osu.files.${VERSION}

    build:
      context: .
      dockerfile: osu.files.Dockerfile
      args:
        - FILE_NAME=${OSU_FILES}
        - WORKDIR=/osu.files
    volumes:
      - osu.files.vol:/osu.files
    profiles:
      - files

volumes:
  osu.mysql.vol:
  osu.files.vol:
