name: Create and Export dataset


on:
  workflow_dispatch:
    inputs:
      year_month_day:
        description: 'Year, month, day of the dataset as YYYY_MM_DD'
        required: true
        default: '2024_01_01'
      mode:
        description: 'Mode of the dataset. (Only mania works)'
        required: true
        default: 'mania'
        type: choice
        options:
          - 'mania'
          - 'taiko'
          - 'catch'
          - 'osu'
      version:
        description: 'Version of the dataset'
        required: true
        default: 'top_1000'
      number_of_attempts:
        description: 'Number of attempts to wait for MySQL to be ready. 
                      Each attempt waits for 10 seconds.'
        required: true
        default: 100

jobs:
  create-dataset:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      DATASET_NAME: ${{ inputs.year_month_day }}_${{ inputs.version }}_${{ inputs.mode }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy[pymysql] numpy pandas tqdm icecream

      - name: Run osu-data
        run: |
          chmod +x ./osu_data/main.py
          nohup python -m osu_data.main \
            -m ${{ inputs.mode }} \
            -v ${{ inputs.version }} \
            -ym ${{ inputs.year_month_day }} &

      - name: Healthcheck osu-data
        shell: bash
        run: |
          chmod +x ./osu_dataset/check_mysql_ready.sh
          ./osu_dataset/check_mysql_ready.sh ${{ inputs.number_of_attempts }}

      - name: Create Dataset and Export
        run: |
          sleep 10
          python -m osu_dataset.create_dataset ${{ env.DATASET_NAME }}.tar.bz2

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.DATASET_NAME }}.tar.bz2
          tag: ${{ env.DATASET_NAME }}
          name: Release ${{ env.DATASET_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
