name: Create and export dataset

on:
  workflow_dispatch:
    inputs:
      year_month:
        description: 'Year and month of the dataset'
        required: true
        default: '2024_01'
      mode:
        description: 'Mode of the dataset'
        required: true
        default: 'mania'
        type: choice
        options:
          - 'mania'
          - 'taiko'
          - 'catch'
          - 'osu'
      version:
        description: 'Version of the dataset'
        required: true
        default: 'top_1000'
      number_of_attempts:
        description: 'Number of attempts to wait for MySQL to be ready. 
                      Each attempt waits for 10 seconds.'
        required: true
        default: 100

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy[pymysql] numpy pandas tqdm

      - name: Run osu-data
        run: |
          chmod +x ./osu_data/main.py
          nohup python -m osu_data.main \
            -m ${{ inputs.mode }} \
            -v ${{ inputs.version }} \
            -ym ${{ inputs.year_month }} &

      - name: Healthcheck osu-data
        shell: bash
        run: |
          chmod +x ./osu_dataset/check_mysql_ready.sh
          ./osu_dataset/check_mysql_ready.sh ${{ inputs.number_of_attempts }}

      - name: Run create_dataset
        run: |
          sleep 10
          python -m osu_dataset.create_dataset

      - name: Run export_dataset
        run: |
          sleep 10
          python -m osu_dataset.export_dataset

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "osu.tar.bz2"
          tag: ${{ inputs.year_month }}_${{ inputs.version }}_${{ inputs.mode }}
          name: Release ${{ inputs.year_month }}_${{ inputs.version }}_${{ inputs.mode }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
