name: Create and export dataset

on:
  workflow_dispatch:
    inputs:
      year_month:
        description: 'Year and month of the dataset'
        required: true
        default: '2024_01'
      mode:
        description: 'Mode of the dataset'
        required: true
        default: 'mania'
        type: choice
        options:
          - 'mania'
          - 'taiko'
          - 'catch'
          - 'osu'
      version:
        description: 'Version of the dataset'
        required: true
        default: 'top_1000'
      number_of_attempts:
        description: 'Number of attempts to wait for MySQL to be ready. 
                      Each attempt waits for 10 seconds.'
        required: true
        default: 100

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy[pymysql] numpy pandas tqdm

      - name: Run osu-data
        run: |
          chmod +x ./osu_data/main.py
          nohup python -m osu_data.main \
            -m ${{ inputs.mode }} \
            -v ${{ inputs.version }} \
            -ym ${{ inputs.year_month }} &

      - name: Wait for osu-data to finish
        run: |
          max_attempts=${{ inputs.number_of_attempts }}
          attempt=0
          while ((attempt < max_attempts))
          do
            # Check if osu-data is running
            if docker ps --format '{{.Names}}' | grep -q "^osu.mysql$"; then
              # Check if MySQL is ready
              if docker logs osu.mysql 2>&1 | grep -q "/usr/sbin/mysqld: ready for connections"; then
                exit 0
              fi
            fi
            echo "Waiting for MySQL to be ready... Attempt $attempt of $max_attempts"
            sleep 10
            ((attempt++))
          done          
          exit 1

      - name: Run create_dataset
        run: python -m osu_dataset.create_dataset

      - name: Run export_dataset
        run: python -m osu_dataset.export_dataset

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "osu.tar.bz2"
          tag: ${{ inputs.year_month }}_${{ inputs.version }}_${{ inputs.mode }}
          name: Release ${{ inputs.year_month }}_${{ inputs.version }}_${{ inputs.mode }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
