name: Docker Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker compose up
      
    - name: Test MySQL
      run:  |
        docker exec -it osu-data-docker-mysql-service-1 \
        mysql -u root --password=p@ssw0rd1 \
        -e "use osu; select * from osu_counts limit 100;"
        
    - name: Test MySQL (Fail)
      run:  |
        docker exec -it osu-data-docker-mysql-service-1 \
        mysql -u root --password=p@ssw0rd1 \
        -e "use osu; select * from osu_counts2 limit 100;"

