name: Docker Compose CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker compose --env-file test/.test.env up --wait

      - name: Install mysql-server
        run: |
          sudo apt-get install mysql-server

      - name: Test MySQL
        run: |
          sleep 5;
          docker exec osu.mysql \
          mysql -u root --password=p@ssw0rd1 \
          -e "use osu; select * from osu_counts limit 100;"

      - name: Stop the Docker Container
        run: |
          docker compose stop

      - name: Build Docker Image with files
        run: |
          docker compose --profile files --env-file test/.test.env up --wait --build

      - name: Test Files Service & Files Folder exist
        run: |
          docker exec osu.files sh -c 'if [ $(ls YYYY_MM_DD_osu_files/ | wc -l) -ge 1 ]; then exit 0; else exit 1; fi'

