name: Get Maps Script CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker compose --profile files --env-file test/.test.env up --wait

      - name: Run get_maps.sh
        run: |
          ./scripts/get_maps.sh -q "SELECT beatmap_id FROM osu_beatmaps LIMIT 100;" -o ./my.tar.bz2

      - name: Check if tar.bz2 exists
        run: |
          [ -f ./my.tar.bz2 ] || exit 1

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: get_maps.tar.bz2
          path: ./my.tar.bz2